import type { ColorFamily } from './colors';
import type { CanSeries, CanVolume } from '@/components/art/SprayCan';
import type { MarkerTip } from '@/components/art/Marker';

/**
 * Catalogue for the mockup.
 *
 * Every product carries an `art` descriptor instead of an image path — the
 * whole catalogue is drawn as vector by `components/art`, so a shade can be
 * added by writing one line here rather than shooting a photo. Prices are
 * realistic Czech retail; codes line up with the MTN codes in `./colors`.
 */

export type ProductKind = 'spray' | 'marker' | 'cap' | 'apparel' | 'accessory';

export type CategorySlug = 'spreje' | 'fixy' | 'trysky' | 'obleceni' | 'doplnky';

export type Badge = 'NOVÉ' | 'BESTSELLER' | 'OMEZENÉ' | 'SLEVA' | 'PACK' | 'TIP';

/** Discriminated union consumed by `components/art/ProductArt`. */
export type ArtSpec =
  | { t: 'can'; series: CanSeries; volume: CanVolume }
  | { t: 'marker'; tip: MarkerTip; finish: 'acrylic' | 'ink' | 'chrome'; label?: string }
  | { t: 'cap'; style: 'fat' | 'skinny' | 'calligraphy' | 'universal' | 'super-fat' }
  | { t: 'apparel'; cut: 'tee' | 'hoodie' | 'cap' | 'crewneck'; print?: string }
  | { t: 'book'; size: 'A4' | 'A5' | 'square' }
  | { t: 'gloves' }
  | { t: 'stencil' }
  | { t: 'bag' }
  | { t: 'refill' };

export type Product = {
  id: string;
  name: string;
  /** Short line under the title in the card. */
  line: string;
  price: number;
  /** Struck-through original — presence drives the SLEVA treatment. */
  oldPrice?: number;
  kind: ProductKind;
  category: CategorySlug;
  /** Primary visual colour: tints the card glow and drives the vector render. */
  hex: string;
  colorCode?: string;
  colorName?: string;
  family?: ColorFamily;
  inStock: boolean;
  /** Drives the "poslední kusy" urgency pill. */
  stock?: number;
  badge?: Badge;
  rating: number;
  reviews: number;
  art: ArtSpec;
  /** MTN codes this item also comes in — rendered as swatch dots on the card. */
  variants?: string[];
  tags?: string[];
};

export const CATEGORIES: { slug: CategorySlug; label: string; blurb: string }[] = [
  { slug: 'spreje', label: 'Spreje', blurb: 'BLACK, GOLD, 94, Chalk, Stencil, Hardcore' },
  { slug: 'fixy', label: 'Fixy & markery', blurb: 'Akrylové, lakové, refilly. 2 až 50 mm.' },
  { slug: 'trysky', label: 'Trysky', blurb: 'Fat, skinny, calligraphy, universal.' },
  { slug: 'obleceni', label: 'Oblečení', blurb: 'Trika, mikiny, kšiltovky.' },
  { slug: 'doplnky', label: 'Doplňky', blurb: 'Blackbooky, rukavice, šablony, brašny.' },
];

export const PRODUCTS: Product[] = [
  /* ── SPREJE ─────────────────────────────────────────────────── */
  {
    id: 'black-400-mandarine',
    name: 'Montana BLACK 400',
    line: 'Mandarine · vysokotlaký',
    price: 179,
    kind: 'spray',
    category: 'spreje',
    hex: '#e25a15',
    colorCode: 'MTN-4030',
    colorName: 'Mandarine',
    family: 'orange',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 214,
    art: { t: 'can', series: 'BLACK', volume: 400 },
    variants: ['MTN-3050', 'MTN-5040', 'MTN-6080', 'MTN-7050'],
    tags: ['vysoký tlak', 'kryje na jeden tah'],
  },
  {
    id: 'black-400-power-green',
    name: 'Montana BLACK 400',
    line: 'Power Green Fluorescent',
    price: 219,
    kind: 'spray',
    category: 'spreje',
    hex: '#39d04a',
    colorCode: 'MTN-6080',
    colorName: 'Acid',
    family: 'green',
    inStock: true,
    stock: 6,
    badge: 'NOVÉ',
    rating: 4.8,
    reviews: 61,
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['fluorescentní'],
  },
  {
    id: 'black-400-tornado',
    name: 'Montana BLACK 400',
    line: 'Tornado Red · vysokotlaký',
    price: 179,
    kind: 'spray',
    category: 'spreje',
    hex: '#d31a25',
    colorCode: 'MTN-3050',
    colorName: 'Tornado',
    family: 'red',
    inStock: true,
    rating: 4.9,
    reviews: 178,
    art: { t: 'can', series: 'BLACK', volume: 400 },
  },
  {
    id: 'black-400-electric',
    name: 'Montana BLACK 400',
    line: 'Electric Blue · vysokotlaký',
    price: 179,
    kind: 'spray',
    category: 'spreje',
    hex: '#1f63e0',
    colorCode: 'MTN-7050',
    colorName: 'Electric',
    family: 'blue',
    inStock: true,
    rating: 4.8,
    reviews: 143,
    art: { t: 'can', series: 'BLACK', volume: 400 },
  },
  {
    id: 'black-400-cadmium',
    name: 'Montana BLACK 400',
    line: 'Cadmium Yellow',
    price: 179,
    kind: 'spray',
    category: 'spreje',
    hex: '#f4c21a',
    colorCode: 'MTN-5040',
    colorName: 'Cadmium',
    family: 'yellow',
    inStock: true,
    rating: 4.7,
    reviews: 96,
    art: { t: 'can', series: 'BLACK', volume: 400 },
  },
  {
    id: 'black-400-carbon',
    name: 'Montana BLACK 400',
    line: 'Carbon · nejtmavší černá',
    price: 169,
    kind: 'spray',
    category: 'spreje',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 5,
    reviews: 402,
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['outline', 'nejprodávanější'],
  },
  {
    id: 'gold-400-peach',
    name: 'Montana GOLD 400',
    line: 'Peach · nízkotlaký, matný',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#ffc481',
    colorCode: 'MTN-4060',
    colorName: 'Peach',
    family: 'orange',
    inStock: true,
    rating: 4.8,
    reviews: 74,
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['nízký tlak', 'detaily'],
  },
  {
    id: 'gold-400-cobalt',
    name: 'Montana GOLD 400',
    line: 'Cobalt · nízkotlaký',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#1a48b6',
    colorCode: 'MTN-7040',
    colorName: 'Cobalt',
    family: 'blue',
    inStock: true,
    rating: 4.9,
    reviews: 118,
    art: { t: 'can', series: 'GOLD', volume: 400 },
  },
  {
    id: 'gold-400-iris',
    name: 'Montana GOLD 400',
    line: 'Iris · nízkotlaký',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#8b46d6',
    colorCode: 'MTN-8040',
    colorName: 'Iris',
    family: 'purple',
    inStock: true,
    rating: 4.7,
    reviews: 52,
    art: { t: 'can', series: 'GOLD', volume: 400 },
  },
  {
    id: 'gold-400-lemon',
    name: 'Montana GOLD 400',
    line: 'Lemon · nízkotlaký',
    price: 199,
    oldPrice: 239,
    kind: 'spray',
    category: 'spreje',
    hex: '#fce53a',
    colorCode: 'MTN-5050',
    colorName: 'Lemon',
    family: 'yellow',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.6,
    reviews: 41,
    art: { t: 'can', series: 'GOLD', volume: 400 },
  },
  {
    id: '94-400-hot-pink',
    name: 'Montana 94 400',
    line: 'Hot Pink · matný finiš',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#ed3a8e',
    colorCode: 'MTN-9030',
    colorName: 'Hot Pink',
    family: 'pink',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 156,
    art: { t: 'can', series: '94', volume: 400 },
    tags: ['matný', 'rychle schne'],
  },
  {
    id: '94-400-cyan',
    name: 'Montana 94 400',
    line: 'Cyan · matný finiš',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#21c4d1',
    colorCode: 'MTN-7090',
    colorName: 'Cyan',
    family: 'blue',
    inStock: true,
    rating: 4.8,
    reviews: 88,
    art: { t: 'can', series: '94', volume: 400 },
  },
  {
    id: '94-400-guacamole',
    name: 'Montana 94 400',
    line: 'Guacamole · matný finiš',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#67b94b',
    colorCode: 'MTN-6070',
    colorName: 'Guacamole',
    family: 'green',
    inStock: false,
    rating: 4.7,
    reviews: 33,
    art: { t: 'can', series: '94', volume: 400 },
  },
  {
    id: '94-400-bordo',
    name: 'Montana 94 400',
    line: 'Bordó · matný finiš',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#7a121f',
    colorCode: 'MTN-3030',
    colorName: 'Bordó',
    family: 'red',
    inStock: true,
    stock: 4,
    rating: 4.8,
    reviews: 27,
    art: { t: 'can', series: '94', volume: 400 },
  },
  {
    id: 'chalk-400-acid',
    name: 'Montana CHALK 400',
    line: 'Acid Green · smývatelný',
    price: 169,
    oldPrice: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#a3d930',
    colorCode: 'MTN-6080',
    colorName: 'Acid',
    family: 'green',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.5,
    reviews: 39,
    art: { t: 'can', series: 'CHALK', volume: 400 },
    tags: ['smyje se vodou', 'legální'],
  },
  {
    id: 'chalk-400-cadmium',
    name: 'Montana CHALK 400',
    line: 'Cadmium · smývatelný',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#f4c21a',
    colorCode: 'MTN-5040',
    colorName: 'Cadmium',
    family: 'yellow',
    inStock: true,
    rating: 4.5,
    reviews: 22,
    art: { t: 'can', series: 'CHALK', volume: 400 },
  },
  {
    id: 'stencil-400-black',
    name: 'Montana STENCIL 400',
    line: 'Black · ultrarychlé schnutí',
    price: 159,
    kind: 'spray',
    category: 'spreje',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 64,
    art: { t: 'can', series: 'STENCIL', volume: 400 },
    tags: ['šablony', 'schne do 8 minut'],
  },
  {
    id: 'stencil-400-chalk',
    name: 'Montana STENCIL 400',
    line: 'Chalk White · na šablony',
    price: 159,
    kind: 'spray',
    category: 'spreje',
    hex: '#f1ede4',
    colorCode: 'MTN-1080',
    colorName: 'Chalk',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 31,
    art: { t: 'can', series: 'STENCIL', volume: 400 },
  },
  {
    id: 'hardcore-600-cyan',
    name: 'Montana HARDCORE 600',
    line: 'Cyan · XL formát',
    price: 289,
    kind: 'spray',
    category: 'spreje',
    hex: '#21c4d1',
    colorCode: 'MTN-7090',
    colorName: 'Cyan',
    family: 'blue',
    inStock: true,
    badge: 'OMEZENÉ',
    stock: 8,
    rating: 4.9,
    reviews: 47,
    art: { t: 'can', series: 'HARDCORE', volume: 600 },
    tags: ['600 ml', 'velké plochy'],
  },
  {
    id: 'hardcore-600-silver',
    name: 'Montana HARDCORE 600',
    line: 'Silver Chrome · XL formát',
    price: 299,
    kind: 'spray',
    category: 'spreje',
    hex: '#9c9aa0',
    colorCode: 'MTN-1060',
    colorName: 'Silver',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 5,
    reviews: 191,
    art: { t: 'can', series: 'HARDCORE', volume: 600 },
    tags: ['chrom', 'fill-in'],
  },
  {
    id: 'water-150-magenta',
    name: 'Montana WATER 150',
    line: 'Magenta · kapesní formát',
    price: 129,
    kind: 'spray',
    category: 'spreje',
    hex: '#d61676',
    colorCode: 'MTN-9020',
    colorName: 'Fuchsia',
    family: 'pink',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.4,
    reviews: 12,
    art: { t: 'can', series: 'WATER', volume: 150 },
    tags: ['vodou ředitelný', 'do kapsy'],
  },
  {
    id: 'water-150-ultramarine',
    name: 'Montana WATER 150',
    line: 'Ultramarine · kapesní formát',
    price: 129,
    kind: 'spray',
    category: 'spreje',
    hex: '#163181',
    colorCode: 'MTN-7030',
    colorName: 'Ultramarine',
    family: 'blue',
    inStock: true,
    rating: 4.4,
    reviews: 9,
    art: { t: 'can', series: 'WATER', volume: 150 },
  },

  /* ── FIXY & MARKERY ─────────────────────────────────────────── */
  {
    id: 'marker-acrylic-15-iris',
    name: 'Acrylic Marker 15 mm',
    line: 'Iris · kryje na tmavé',
    price: 289,
    kind: 'marker',
    category: 'fixy',
    hex: '#8b46d6',
    colorCode: 'MTN-8040',
    colorName: 'Iris',
    family: 'purple',
    inStock: true,
    rating: 4.8,
    reviews: 83,
    art: { t: 'marker', tip: 15, finish: 'acrylic', label: 'ACRYLIC' },
    variants: ['MTN-9030', 'MTN-7040', 'MTN-6080'],
  },
  {
    id: 'marker-acrylic-15-hotpink',
    name: 'Acrylic Marker 15 mm',
    line: 'Hot Pink · kryje na tmavé',
    price: 289,
    kind: 'marker',
    category: 'fixy',
    hex: '#ed3a8e',
    colorCode: 'MTN-9030',
    colorName: 'Hot Pink',
    family: 'pink',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 127,
    art: { t: 'marker', tip: 15, finish: 'acrylic', label: 'ACRYLIC' },
  },
  {
    id: 'marker-acrylic-2-tornado',
    name: 'Acrylic Marker 2 mm',
    line: 'Tornado Red · linky a detaily',
    price: 219,
    kind: 'marker',
    category: 'fixy',
    hex: '#d31a25',
    colorCode: 'MTN-3050',
    colorName: 'Tornado',
    family: 'red',
    inStock: true,
    rating: 4.7,
    reviews: 58,
    art: { t: 'marker', tip: 2, finish: 'acrylic', label: 'ACRYLIC' },
  },
  {
    id: 'marker-acrylic-30-cobalt',
    name: 'Acrylic Marker 30 mm',
    line: 'Cobalt · široké tahy',
    price: 389,
    kind: 'marker',
    category: 'fixy',
    hex: '#1a48b6',
    colorCode: 'MTN-7040',
    colorName: 'Cobalt',
    family: 'blue',
    inStock: true,
    rating: 4.8,
    reviews: 44,
    art: { t: 'marker', tip: 30, finish: 'acrylic', label: 'ACRYLIC' },
  },
  {
    id: 'marker-acrylic-50-carbon',
    name: 'Acrylic Marker 50 mm',
    line: 'Carbon · fill-in marker',
    price: 549,
    kind: 'marker',
    category: 'fixy',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 71,
    art: { t: 'marker', tip: 50, finish: 'ink', label: 'FILL IN' },
    tags: ['nejširší nib', 'na plochy'],
  },
  {
    id: 'marker-ink-15-black',
    name: 'Permanent Marker 15 mm',
    line: 'Black · lihový, na všechno',
    price: 249,
    kind: 'marker',
    category: 'fixy',
    hex: '#17161c',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 164,
    art: { t: 'marker', tip: 15, finish: 'ink', label: 'PERMANENT' },
  },
  {
    id: 'marker-chrome-5',
    name: 'Chrome Marker 5 mm',
    line: 'Silver · zrcadlový efekt',
    price: 349,
    kind: 'marker',
    category: 'fixy',
    hex: '#b6b6c0',
    colorCode: 'MTN-1060',
    colorName: 'Silver',
    family: 'neutral',
    inStock: true,
    badge: 'OMEZENÉ',
    stock: 5,
    rating: 4.9,
    reviews: 92,
    art: { t: 'marker', tip: 5, finish: 'chrome', label: 'CHROME' },
    tags: ['zrcadlová stříbrná'],
  },
  {
    id: 'marker-acrylic-5-acid',
    name: 'Acrylic Marker 5 mm',
    line: 'Acid · na skice i stěnu',
    price: 239,
    kind: 'marker',
    category: 'fixy',
    hex: '#a3d930',
    colorCode: 'MTN-6080',
    colorName: 'Acid',
    family: 'green',
    inStock: true,
    rating: 4.6,
    reviews: 37,
    art: { t: 'marker', tip: 5, finish: 'acrylic', label: 'ACRYLIC' },
  },
  {
    id: 'marker-set-basic',
    name: 'Marker set ZÁKLAD (6 ks)',
    line: '2 / 5 / 15 mm · černá + barvy',
    price: 1290,
    oldPrice: 1590,
    kind: 'marker',
    category: 'fixy',
    hex: '#f4c21a',
    family: 'yellow',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.9,
    reviews: 54,
    art: { t: 'marker', tip: 15, finish: 'acrylic', label: 'SET 6' },
    tags: ['startovací set'],
  },
  {
    id: 'refill-acrylic-carbon',
    name: 'Refill 200 ml',
    line: 'Carbon · dolití akrylového fixu',
    price: 249,
    kind: 'marker',
    category: 'fixy',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 48,
    art: { t: 'refill' },
    tags: ['úspornější než nový fix'],
  },

  /* ── TRYSKY ─────────────────────────────────────────────────── */
  {
    id: 'cap-fat-10',
    name: 'Fat Cap (10 ks)',
    line: 'Široký nástřik · 4–6 cm',
    price: 159,
    kind: 'cap',
    category: 'trysky',
    hex: '#ff8a2a',
    inStock: true,
    badge: 'PACK',
    rating: 4.8,
    reviews: 96,
    art: { t: 'cap', style: 'fat' },
    tags: ['fill-in'],
  },
  {
    id: 'cap-skinny-10',
    name: 'Skinny Cap (10 ks)',
    line: 'Tenká linka · 8–15 mm',
    price: 169,
    kind: 'cap',
    category: 'trysky',
    hex: '#c9a23b',
    inStock: true,
    badge: 'PACK',
    rating: 4.9,
    reviews: 141,
    art: { t: 'cap', style: 'skinny' },
    tags: ['outline'],
  },
  {
    id: 'cap-universal-10',
    name: 'Universal Cap (10 ks)',
    line: 'Univerzál · sedí na vše',
    price: 149,
    kind: 'cap',
    category: 'trysky',
    hex: '#a3d930',
    family: 'green',
    inStock: true,
    badge: 'PACK',
    rating: 4.6,
    reviews: 73,
    art: { t: 'cap', style: 'universal' },
  },
  {
    id: 'cap-calligraphy-5',
    name: 'Calligraphy Cap (5 ks)',
    line: 'Plochý nástřik · kaligrafie',
    price: 139,
    kind: 'cap',
    category: 'trysky',
    hex: '#d31a25',
    family: 'red',
    inStock: true,
    rating: 4.7,
    reviews: 34,
    art: { t: 'cap', style: 'calligraphy' },
    tags: ['ploché tahy'],
  },
  {
    id: 'cap-superfat-5',
    name: 'Super Fat Cap (5 ks)',
    line: 'Nejširší nástřik · 8–12 cm',
    price: 179,
    kind: 'cap',
    category: 'trysky',
    hex: '#1f63e0',
    family: 'blue',
    inStock: true,
    rating: 4.8,
    reviews: 58,
    art: { t: 'cap', style: 'super-fat' },
  },
  {
    id: 'cap-mix-30',
    name: 'Cap MIX BOX (30 ks)',
    line: 'Od skinny po super fat',
    price: 429,
    oldPrice: 519,
    kind: 'cap',
    category: 'trysky',
    hex: '#ed3a8e',
    family: 'pink',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.9,
    reviews: 112,
    art: { t: 'cap', style: 'fat' },
    tags: ['vyzkoušej všechno'],
  },
  {
    id: 'cap-skinny-precision',
    name: 'Skinny Precision (10 ks)',
    line: 'Nejtenčí linka · 5–8 mm',
    price: 189,
    kind: 'cap',
    category: 'trysky',
    hex: '#8b46d6',
    family: 'purple',
    inStock: false,
    rating: 4.7,
    reviews: 29,
    art: { t: 'cap', style: 'skinny' },
  },
  {
    id: 'cap-fat-soft',
    name: 'Soft Fat Cap (10 ks)',
    line: 'Měkký přechod · fade',
    price: 169,
    kind: 'cap',
    category: 'trysky',
    hex: '#21c4d1',
    family: 'blue',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 47,
    art: { t: 'cap', style: 'fat' },
    tags: ['fady a přechody'],
  },

  /* ── OBLEČENÍ ───────────────────────────────────────────────── */
  {
    id: 'tee-tag-black',
    name: 'Tričko TAG',
    line: 'Heavy 240 gsm · oversize',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.7,
    reviews: 63,
    art: { t: 'apparel', cut: 'tee', print: 'TAG' },
    tags: ['S–XXL'],
  },
  {
    id: 'tee-throwup-bone',
    name: 'Tričko THROW-UP',
    line: 'Heavy 240 gsm · přírodní bílá',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#efece4',
    family: 'neutral',
    inStock: true,
    rating: 4.6,
    reviews: 41,
    art: { t: 'apparel', cut: 'tee', print: 'THROW' },
  },
  {
    id: 'hoodie-blackbook',
    name: 'Mikina BLACKBOOK',
    line: '380 gsm · heavy oversize',
    price: 1490,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#0e0d10',
    family: 'neutral',
    inStock: true,
    badge: 'OMEZENÉ',
    stock: 7,
    rating: 4.9,
    reviews: 88,
    art: { t: 'apparel', cut: 'hoodie', print: 'MTN' },
    tags: ['klokaní kapsa'],
  },
  {
    id: 'hoodie-acid',
    name: 'Mikina ACID',
    line: '380 gsm · Acid Green potisk',
    price: 1590,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#25232c',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 34,
    art: { t: 'apparel', cut: 'hoodie', print: 'ACID' },
  },
  {
    id: 'crewneck-brno',
    name: 'Mikina BRNO CREW',
    line: '340 gsm · bez kapuce',
    price: 1290,
    oldPrice: 1490,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#46434a',
    family: 'neutral',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.7,
    reviews: 26,
    art: { t: 'apparel', cut: 'crewneck', print: 'BRNO' },
  },
  {
    id: 'snapback-mtn',
    name: 'Kšiltovka MTN 6-PANEL',
    line: 'Snapback · vyšívané logo',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#131218',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 57,
    art: { t: 'apparel', cut: 'cap', print: 'MTN' },
  },
  {
    id: 'snapback-tape',
    name: 'Kšiltovka TAPE',
    line: 'Snapback · tape yellow',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.6,
    reviews: 18,
    art: { t: 'apparel', cut: 'cap', print: 'MTN' },
  },

  /* ── DOPLŇKY ────────────────────────────────────────────────── */
  {
    id: 'blackbook-a4',
    name: 'Blackbook A4',
    line: 'Portrait · 144 stran, 120 g',
    price: 549,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#1f1d24',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 203,
    art: { t: 'book', size: 'A4' },
    tags: ['tvrdé desky', 'gumička'],
  },
  {
    id: 'blackbook-a5',
    name: 'Blackbook A5',
    line: 'Do kapsy · 144 stran',
    price: 349,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#2a282e',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 97,
    art: { t: 'book', size: 'A5' },
  },
  {
    id: 'blackbook-square-tape',
    name: 'Blackbook SQUARE',
    line: 'Čtvercový · žluté desky',
    price: 429,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.7,
    reviews: 21,
    art: { t: 'book', size: 'square' },
  },
  {
    id: 'gloves-nitrile',
    name: 'Nitrilové rukavice (50 párů)',
    line: 'Černé · odolné rozpouštědlům',
    price: 219,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 84,
    art: { t: 'gloves' },
  },
  {
    id: 'gloves-winter',
    name: 'Zimní rukavice WRITER',
    line: 'Zateplené · prst na trysku',
    price: 490,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#34313c',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 39,
    art: { t: 'gloves' },
    tags: ['na zimní session'],
  },
  {
    id: 'stencil-alphabet',
    name: 'Šablona ABECEDA',
    line: 'Mylar 250 µm · A3',
    price: 249,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#f1ede4',
    family: 'neutral',
    inStock: true,
    rating: 4.5,
    reviews: 26,
    art: { t: 'stencil' },
  },
  {
    id: 'stencil-custom',
    name: 'Šablona NA MÍRU',
    line: 'Řezaná podle tvého návrhu',
    price: 690,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#ff2d4a',
    family: 'red',
    inStock: true,
    badge: 'OMEZENÉ',
    rating: 5,
    reviews: 14,
    art: { t: 'stencil' },
    tags: ['dodání 5 dní'],
  },
  {
    id: 'bag-can-12',
    name: 'Brašna na 12 sprejů',
    line: 'Canvas 600D · nastavitelný popruh',
    price: 990,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#25232c',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 118,
    art: { t: 'bag' },
    tags: ['tichý zip'],
  },
  {
    id: 'bag-daypack',
    name: 'Batoh DAYPACK 22 l',
    line: 'Vyztužené dno · na 8 sprejů',
    price: 1290,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#0e0d10',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 62,
    art: { t: 'bag' },
  },
];

/** Sort modes offered in the catalogue toolbar. */
export type SortMode = 'doporucene' | 'nejlevnejsi' | 'nejdrazsi' | 'hodnoceni' | 'novinky';

export const SORTS: { id: SortMode; label: string }[] = [
  { id: 'doporucene', label: 'Doporučené' },
  { id: 'novinky', label: 'Novinky' },
  { id: 'nejlevnejsi', label: 'Nejlevnější' },
  { id: 'nejdrazsi', label: 'Nejdražší' },
  { id: 'hodnoceni', label: 'Nejlépe hodnocené' },
];

export function sortProducts(list: Product[], mode: SortMode): Product[] {
  const out = [...list];
  switch (mode) {
    case 'nejlevnejsi':
      return out.sort((a, b) => a.price - b.price);
    case 'nejdrazsi':
      return out.sort((a, b) => b.price - a.price);
    case 'hodnoceni':
      return out.sort((a, b) => b.rating - a.rating || b.reviews - a.reviews);
    case 'novinky':
      return out.sort(
        (a, b) => Number(b.badge === 'NOVÉ') - Number(a.badge === 'NOVÉ') || b.reviews - a.reviews,
      );
    default:
      /* "Doporučené" = in stock first, then by how much social proof it has. */
      return out.sort(
        (a, b) => Number(b.inStock) - Number(a.inStock) || b.reviews - a.reviews,
      );
  }
}

/** Czech price formatting — non-breaking space before the currency. */
export function formatPrice(czk: number): string {
  return `${czk.toLocaleString('cs-CZ')} Kč`;
}
