import type { ColorFamily } from './colors';
import type { CanSeries, CanVolume } from '@/components/art/SprayCan';
import type { MarkerTip } from '@/components/art/Marker';

export type ProductKind = 'spray' | 'marker' | 'cap' | 'apparel' | 'accessory';

export type CategorySlug = 'spreje' | 'fixy' | 'trysky' | 'obleceni' | 'doplnky';

export type Badge = 'NOVÉ' | 'BESTSELLER' | 'OMEZENÉ' | 'SLEVA' | 'PACK' | 'TIP';

/** Discriminated union for backward compatibility with art renderers. */
export type ArtSpec =
  | { t: 'can'; series: CanSeries; volume: CanVolume }
  | { t: 'marker'; tip: MarkerTip; finish: 'acrylic' | 'ink' | 'chrome'; label?: string }
  | { t: 'cap'; style: 'fat' | 'skinny' | 'calligraphy' | 'universal' | 'super-fat' }
  | { t: 'apparel'; cut: 'tee' | 'hoodie' | 'cap' | 'crewneck'; print?: string }
  | { t: 'book'; size: 'A4' | 'A5' | 'square' }
  | { t: 'gloves' }
  | { t: 'stencil' }
  | { t: 'bag' }
  | { t: 'refill' };

export type Product = {
  id: string;
  name: string;
  /** Short line under the title in the card. */
  line: string;
  price: number;
  /** Struck-through original — presence drives the SLEVA treatment. */
  oldPrice?: number;
  kind: ProductKind;
  category: CategorySlug;
  /** Primary visual colour: tints the card glow and drives the swatch. */
  hex: string;
  colorCode?: string;
  colorName?: string;
  family?: ColorFamily;
  inStock: boolean;
  /** Drives the "poslední kusy" urgency pill. */
  stock?: number;
  badge?: Badge;
  rating: number;
  reviews: number;
  /** WebP image path relative to public directory. */
  image: string;
  art?: ArtSpec;
  /** MTN codes this item also comes in — rendered as swatch dots on the card. */
  variants?: string[];
  tags?: string[];
};

export const CATEGORIES: { slug: CategorySlug; label: string; blurb: string }[] = [
  { slug: 'spreje', label: 'Spreje', blurb: 'BLACK, GOLD, 94, Chalk, Tech Primery, Loop, Kobra, Dope' },
  { slug: 'fixy', label: 'Fixy & markery', blurb: 'POSCA, Uni Paint, OTR, Krink, Dope Solid, Refilly.' },
  { slug: 'trysky', label: 'Trysky', blurb: 'Level 1–6, Fat, Skinny, Calligraphy, Astro, NY Fat.' },
  { slug: 'obleceni', label: 'Oblečení', blurb: 'Originální Montana trika a mikiny s kapucí.' },
  { slug: 'doplnky', label: 'Doplňky', blurb: 'Blackbooky, brašny Mr. Serious, rukavice, knihy, nálepky.' },
];

export const PRODUCTS: Product[] = [
  /* ── SPREJE ─────────────────────────────────────────────────── */
  {
    id: 'montana-black-400-mandarine',
    name: 'Montana BLACK 400ml',
    line: 'Mandarine · vysokotlaký nitro-kombi lak',
    price: 179,
    kind: 'spray',
    category: 'spreje',
    hex: '#e25a15',
    colorCode: 'MTN-4030',
    colorName: 'Mandarine',
    family: 'orange',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 214,
    image: '/products/montana-black-400.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    variants: ['MTN-3050', 'MTN-5040', 'MTN-6080', 'MTN-7050', 'MTN-1010'],
    tags: ['vysoký tlak', 'kryje na jeden tah', '187 odstínů'],
  },
  {
    id: 'montana-black-400-infra',
    name: 'Montana BLACK Infra 400ml',
    line: 'Fluorescentní odstíny · vysoký tlak',
    price: 219,
    kind: 'spray',
    category: 'spreje',
    hex: '#39d04a',
    colorCode: 'MTN-6080',
    colorName: 'Acid',
    family: 'green',
    inStock: true,
    stock: 6,
    badge: 'NOVÉ',
    rating: 4.8,
    reviews: 61,
    image: '/products/montana-black-infra.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['fluorescentní', 'svítí pod UV'],
  },
  {
    id: 'montana-black-600',
    name: 'Montana BLACK 600ml Maxi',
    line: 'XL formát · vysokotlaký na velké plochy',
    price: 249,
    kind: 'spray',
    category: 'spreje',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 185,
    image: '/products/montana-black-600.webp',
    art: { t: 'can', series: 'BLACK', volume: 600 },
    tags: ['600 ml', 'rychlý fill-in', 'vysoký tlak'],
  },
  {
    id: 'montana-black-150-pocket',
    name: 'Montana BLACK 150ml Pocket',
    line: 'Kapesní formát · vysokotlaký',
    price: 139,
    kind: 'spray',
    category: 'spreje',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 92,
    image: '/products/montana-black-150.webp',
    art: { t: 'can', series: 'BLACK', volume: 150 },
    tags: ['do kapsy', 'diskrétní formát'],
  },
  {
    id: 'montana-black-50-mini',
    name: 'Montana BLACK 50ml Micro',
    line: 'Miniaturní sprej 50 ml · sběratelský & ultra skladný',
    price: 109,
    kind: 'spray',
    category: 'spreje',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 43,
    image: '/products/montana-black-50.webp',
    art: { t: 'can', series: 'BLACK', volume: 150 },
    tags: ['50 ml', 'micro can', 'do dlaně'],
  },
  {
    id: 'montana-gold-400-cobalt',
    name: 'Montana GOLD 400ml',
    line: 'Nízkotlaký pololesklý akrylový sprej pro detailní tvorbu',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#1a48b6',
    colorCode: 'MTN-7040',
    colorName: 'Cobalt',
    family: 'blue',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 168,
    image: '/products/montana-gold-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    variants: ['MTN-4060', 'MTN-7040', 'MTN-8040', 'MTN-5050'],
    tags: ['nízký tlak', 'jemné linky', '215 odstínů'],
  },
  {
    id: 'montana-gold-400-fire-red',
    name: 'Montana GOLD 400ml Fire Red',
    line: 'Fire Red · sytý červený matný tón',
    price: 199,
    oldPrice: 229,
    kind: 'spray',
    category: 'spreje',
    hex: '#d31a25',
    colorCode: 'MTN-3050',
    colorName: 'Tornado',
    family: 'red',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.8,
    reviews: 54,
    image: '/products/montana-gold-fire-red.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['nízký tlak', 'akrylátový lak'],
  },
  {
    id: 'montana-94-400',
    name: 'Montana 94 400ml',
    line: 'Matný syntetický lak · nízký tlak a ultra kryvost',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#ed3a8e',
    colorCode: 'MTN-9030',
    colorName: 'Hot Pink',
    family: 'pink',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 156,
    image: '/products/montana-94-400.webp',
    art: { t: 'can', series: '94', volume: 400 },
    variants: ['MTN-7090', 'MTN-6070', 'MTN-3030'],
    tags: ['matný finiš', 'rychleschnoucí', 'španělská klasika'],
  },
  {
    id: 'montana-chalk-400',
    name: 'Montana CHALK 400ml',
    line: 'Smývatelný křídový sprej · na chodníky, sklo i akce',
    price: 169,
    oldPrice: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#a3d930',
    colorCode: 'MTN-6080',
    colorName: 'Acid',
    family: 'green',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.6,
    reviews: 47,
    image: '/products/montana-chalk-400.webp',
    art: { t: 'can', series: 'CHALK', volume: 400 },
    tags: ['smyje se vodou', 'legální akce', 'chodníky'],
  },
  {
    id: 'montana-whiteout-400',
    name: 'Montana WHITEOUT 400ml',
    line: 'Extra krycí bílá · ultra pigmentace a matný finish',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#f7f7f9',
    colorCode: 'MTN-1080',
    colorName: 'Chalk',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 5.0,
    reviews: 112,
    image: '/products/montana-whiteout-400.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['maximální kryvost', 'čistá bílá', 'podklad'],
  },
  {
    id: 'montana-ultrawide-750',
    name: 'Montana ULTRA-WIDE 750ml',
    line: 'Extrémní tlak & stopa až 50 cm · na mega plochy',
    price: 299,
    kind: 'spray',
    category: 'spreje',
    hex: '#1f63e0',
    colorCode: 'MTN-7050',
    colorName: 'Electric',
    family: 'blue',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 138,
    image: '/products/montana-ultrawide-750.webp',
    art: { t: 'can', series: 'HARDCORE', volume: 600 },
    tags: ['750 ml', 'stopa 50 cm', 'ultra tlak'],
  },
  {
    id: 'montana-silverchrome-600',
    name: 'Montana SILVERCHROME 600ml',
    line: 'Zrcadlový chrom s vysokým tlakem · kryje na první tah',
    price: 249,
    kind: 'spray',
    category: 'spreje',
    hex: '#c0c0c8',
    colorCode: 'MTN-1060',
    colorName: 'Silver',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 204,
    image: '/products/montana-silverchrome-600.webp',
    art: { t: 'can', series: 'BLACK', volume: 600 },
    tags: ['chrom', 'zrcadlový lesk', '600 ml'],
  },
  {
    id: 'montana-tarblack-500',
    name: 'Montana TARBLACK 500ml',
    line: 'Asfaltová černá · kryje mokrý chrom bez vsakování',
    price: 219,
    kind: 'spray',
    category: 'spreje',
    hex: '#121214',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 89,
    image: '/products/montana-tarblack-500.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['asfaltový lak', 'přes čerstvý chrom', '500 ml'],
  },
  {
    id: 'montana-granit-400',
    name: 'Montana GRANIT Effect 400ml',
    line: 'Speciální efekt přírodní žuly a kamene',
    price: 259,
    kind: 'spray',
    category: 'spreje',
    hex: '#7d7c80',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 32,
    image: '/products/montana-granit-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['efektový sprej', 'kamenný povrch'],
  },
  {
    id: 'montana-marble-400',
    name: 'Montana MARBLE Effect 400ml',
    line: 'Mramorový efekt · jemná pavučinová textura',
    price: 259,
    kind: 'spray',
    category: 'spreje',
    hex: '#e8e5df',
    family: 'neutral',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.8,
    reviews: 41,
    image: '/products/montana-marble-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['mramor', 'dekorační efekt'],
  },
  {
    id: 'montana-crackle-400',
    name: 'Montana CRACKLE Effect 400ml',
    line: 'Popraskaný vintage efekt lakovaného povrchu',
    price: 259,
    kind: 'spray',
    category: 'spreje',
    hex: '#8c6b4e',
    family: 'neutral',
    inStock: true,
    rating: 4.6,
    reviews: 28,
    image: '/products/montana-crackle-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['praskající lak', 'vintage'],
  },
  {
    id: 'montana-rust-400',
    name: 'Montana RUST Effect 400ml',
    line: 'Autentický efekt rezavého a oxidovaného kovu',
    price: 259,
    kind: 'spray',
    category: 'spreje',
    hex: '#a3431f',
    family: 'orange',
    inStock: true,
    rating: 4.7,
    reviews: 35,
    image: '/products/montana-rust-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['efekt koroze', 'patina'],
  },
  {
    id: 'montana-nightglow-400',
    name: 'Montana NIGHTGLOW 400ml',
    line: 'Luminiscenční sprej · svítí v absolutní tmě',
    price: 299,
    kind: 'spray',
    category: 'spreje',
    hex: '#c4f250',
    family: 'green',
    inStock: true,
    stock: 5,
    badge: 'OMEZENÉ',
    rating: 4.8,
    reviews: 51,
    image: '/products/montana-nightglow-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['fosforeskující', 'svítí ve tmě'],
  },
  {
    id: 'montana-uv-effect-400',
    name: 'Montana UV EFFECT 400ml',
    line: 'Bezbarvý lak zářící pod UV černým světlem',
    price: 279,
    kind: 'spray',
    category: 'spreje',
    hex: '#5e38d4',
    family: 'purple',
    inStock: true,
    rating: 4.7,
    reviews: 39,
    image: '/products/montana-uv-effect-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['UV světlo', 'neviditelný ve dne'],
  },
  {
    id: 'montana-varnish-400',
    name: 'Montana VARNISH 400ml',
    line: 'Bezbarvý akrylový ochranný lak s UV filtrem',
    price: 199,
    kind: 'spray',
    category: 'spreje',
    hex: '#ece9e2',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 94,
    image: '/products/montana-varnish-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['ochrana před UV', 'mat / lesk'],
  },
  {
    id: 'montana-acetone-400',
    name: 'Montana ACETONE 400ml',
    line: 'Univerzální technický čistič a odmašťovač podkladů',
    price: 169,
    kind: 'spray',
    category: 'spreje',
    hex: '#d0d2d6',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 68,
    image: '/products/montana-acetone-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['čištění trysek', 'odmaštění'],
  },
  {
    id: 'montana-remover-400',
    name: 'Montana REMOVER 400ml',
    line: 'Sprejový odstraňovač starých nátěrů a laků',
    price: 229,
    kind: 'spray',
    category: 'spreje',
    hex: '#9c9da0',
    family: 'neutral',
    inStock: true,
    rating: 4.6,
    reviews: 37,
    image: '/products/montana-remover-400.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['odstranění barvy', 'rychlý účinek'],
  },
  {
    id: 'montana-tech-primer-plastic',
    name: 'Montana TECH Primer Plast 400ml',
    line: 'Základový lak pro dokonalou přilnavost na plasty',
    price: 219,
    kind: 'spray',
    category: 'spreje',
    hex: '#c8c6c1',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 46,
    image: '/products/montana-tech-primer-plastic.webp',
    art: { t: 'can', series: 'GOLD', volume: 400 },
    tags: ['primer na plast', 't2200'],
  },
  {
    id: 'loop-colors-400',
    name: 'Loop Colors 400ml',
    line: 'Italský prémiový akrylový sprej · jemný ventil',
    price: 169,
    kind: 'spray',
    category: 'spreje',
    hex: '#d31a25',
    colorCode: 'MTN-3050',
    colorName: 'Tornado',
    family: 'red',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.8,
    reviews: 114,
    image: '/products/loop-400.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['100% akryl', 'italská výroba', 'přesný ventil'],
  },
  {
    id: 'loop-colors-600-asphalt',
    name: 'Loop Colors 600ml Asphalt',
    line: 'Asphaltová černá 600 ml · brutální tlak',
    price: 229,
    kind: 'spray',
    category: 'spreje',
    hex: '#1a191d',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 82,
    image: '/products/loop-600-asphalt.webp',
    art: { t: 'can', series: 'BLACK', volume: 600 },
    tags: ['asphalt', '600 ml', 'mega stopa'],
  },
  {
    id: 'loop-colors-600-4pack',
    name: 'Loop Colors 600ml (4-PACK)',
    line: 'Výhodný set 4× 600ml sprejů',
    price: 799,
    oldPrice: 916,
    kind: 'spray',
    category: 'spreje',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    badge: 'PACK',
    rating: 4.9,
    reviews: 67,
    image: '/products/loop-600-4pack.webp',
    art: { t: 'can', series: 'BLACK', volume: 600 },
    tags: ['výhodný balíček', '4 kusy v balení'],
  },
  {
    id: 'dope-nitro-500',
    name: 'Dope Nitro 500ml',
    line: 'Vysokotlaký nitro sprej pro rychlou akci',
    price: 189,
    kind: 'spray',
    category: 'spreje',
    hex: '#101014',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 58,
    image: '/products/dope-nitro-500.webp',
    art: { t: 'can', series: 'BLACK', volume: 400 },
    tags: ['nitro kombi', '500 ml', 'vysoký tlak'],
  },
  {
    id: 'kobra-600-spray',
    name: 'Kobra 600ml Big Can',
    line: 'Italský sprej s vysokým výtlakem a sytým pigmentem',
    price: 239,
    kind: 'spray',
    category: 'spreje',
    hex: '#18181c',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 73,
    image: '/products/kobra-600.webp',
    art: { t: 'can', series: 'BLACK', volume: 600 },
    tags: ['600 ml', 'vysoký tlak'],
  },

  /* ── FIXY & MARKERY ─────────────────────────────────────────── */
  {
    id: 'uni-posca-pc-1mc',
    name: 'Uni POSCA PC-1MC',
    line: 'Hrot 0.7–1 mm kónický · na detailní linky',
    price: 119,
    kind: 'marker',
    category: 'fixy',
    hex: '#ed3a8e',
    colorCode: 'MTN-9030',
    colorName: 'Hot Pink',
    family: 'pink',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 142,
    image: '/products/posca-pc-1mc.webp',
    art: { t: 'marker', tip: 2, finish: 'acrylic', label: 'POSCA 1MC' },
    tags: ['vodní báze', 'kryje na tmavé', 'na všechny povrchy'],
  },
  {
    id: 'uni-posca-pc-1mr',
    name: 'Uni POSCA PC-1MR',
    line: 'Extra tenký kalibrovaný hrot 0.7 mm v kovové objímce',
    price: 129,
    kind: 'marker',
    category: 'fixy',
    hex: '#d31a25',
    colorCode: 'MTN-3050',
    colorName: 'Tornado',
    family: 'red',
    inStock: true,
    rating: 4.8,
    reviews: 97,
    image: '/products/posca-pc-1mr.webp',
    art: { t: 'marker', tip: 2, finish: 'acrylic', label: 'POSCA 1MR' },
    tags: ['technické linky', '0.7 mm hrot'],
  },
  {
    id: 'uni-posca-pc-5m-set-10',
    name: 'Uni POSCA PC-5M Set (10 ks)',
    line: 'Nejoblíbenější sada 10 základních odstínů · hrot 1.8–2.5 mm',
    price: 990,
    oldPrice: 1190,
    kind: 'marker',
    category: 'fixy',
    hex: '#f4c21a',
    family: 'yellow',
    inStock: true,
    badge: 'SLEVA',
    rating: 5.0,
    reviews: 89,
    image: '/products/posca-pc-5m-set.webp',
    art: { t: 'marker', tip: 5, finish: 'acrylic', label: 'SET 10' },
    tags: ['10 ks v sadě', 'střední hrot', 'startovací set'],
  },
  {
    id: 'uni-posca-pc-7m',
    name: 'Uni POSCA PC-7M',
    line: 'Široký kónický hrot 4.5–5.5 mm na střední a velké plochy',
    price: 169,
    kind: 'marker',
    category: 'fixy',
    hex: '#1a48b6',
    colorCode: 'MTN-7040',
    colorName: 'Cobalt',
    family: 'blue',
    inStock: true,
    rating: 4.8,
    reviews: 76,
    image: '/products/posca-pc-7m.webp',
    art: { t: 'marker', tip: 15, finish: 'acrylic', label: 'POSCA 7M' },
    tags: ['široký hrot', 'akrylový pigment'],
  },
  {
    id: 'uni-posca-pc-17k',
    name: 'Uni POSCA PC-17K',
    line: 'Extra široký plochý hrot 15 mm na plakáty a tabule',
    price: 249,
    kind: 'marker',
    category: 'fixy',
    hex: '#0e0d10',
    colorCode: 'MTN-1010',
    colorName: 'Carbon',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 84,
    image: '/products/posca-pc-17k.webp',
    art: { t: 'marker', tip: 30, finish: 'acrylic', label: 'POSCA 17K' },
    tags: ['15 mm nib', 'velké plochy'],
  },
  {
    id: 'uni-posca-mop-pcm-22',
    name: 'Uni POSCA MOP\'R PCM-22',
    line: 'Kulatý houbičkový hrot pro drip efekty a tagy',
    price: 229,
    kind: 'marker',
    category: 'fixy',
    hex: '#17161c',
    family: 'neutral',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.9,
    reviews: 63,
    image: '/products/posca-mop-pcm-22.webp',
    art: { t: 'marker', tip: 30, finish: 'acrylic', label: 'MOP\'R' },
    tags: ['drip mop', 'tekutý efekt', 'houbička'],
  },
  {
    id: 'uni-paint-px-20',
    name: 'Uni Paint Marker PX-20',
    line: 'Průmyslový lakový marker · drží na kovu, skle i mastnotě',
    price: 109,
    kind: 'marker',
    category: 'fixy',
    hex: '#f4c21a',
    colorCode: 'MTN-5040',
    colorName: 'Cadmium',
    family: 'yellow',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 178,
    image: '/products/uni-paint-px-20.webp',
    art: { t: 'marker', tip: 5, finish: 'ink', label: 'PX-20' },
    tags: ['olejový lak', 'nesmyatelný', '2.2 mm'],
  },
  {
    id: 'uni-paint-px-21',
    name: 'Uni Paint Marker PX-21',
    line: 'Jemný lakový popisovač · hrot 0.8–1.2 mm',
    price: 99,
    kind: 'marker',
    category: 'fixy',
    hex: '#f1ede4',
    colorCode: 'MTN-1080',
    colorName: 'Chalk',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 116,
    image: '/products/uni-paint-px-21.webp',
    art: { t: 'marker', tip: 2, finish: 'ink', label: 'PX-21' },
    tags: ['tenký lakový', 'kovový hrot'],
  },
  {
    id: 'uni-paint-px-203',
    name: 'Uni Paint Marker PX-203 Extra Fine',
    line: 'Extra jemný jehlový hrot 0.8 mm na detailní popis',
    price: 119,
    kind: 'marker',
    category: 'fixy',
    hex: '#ffffff',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 48,
    image: '/products/uni-paint-px-203.webp',
    art: { t: 'marker', tip: 2, finish: 'ink', label: 'PX-203' },
    tags: ['0.8 mm jehla', 'precizní lak'],
  },
  {
    id: 'otr-8190-whiteout',
    name: 'On The Run OTR.8190 Whiteout',
    line: 'Kapesní korekční pumpovací marker s ultra bílou barvou',
    price: 149,
    kind: 'marker',
    category: 'fixy',
    hex: '#f5f5f7',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 72,
    image: '/products/otr-8190-whiteout.webp',
    art: { t: 'marker', tip: 5, finish: 'acrylic', label: 'OTR 8190' },
    tags: ['whiteout', 'pumpovací', 'rychlé krytí'],
  },
  {
    id: 'otr-8001-metal-tip',
    name: 'On The Run OTR.8001 Metal Tip',
    line: 'Kovový kuličkový hrot · píše na drsný beton i rez',
    price: 169,
    kind: 'marker',
    category: 'fixy',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 128,
    image: '/products/otr-8001-metal-tip.webp',
    art: { t: 'marker', tip: 5, finish: 'ink', label: 'OTR 8001' },
    tags: ['kovový hrot', 'na drsné povrchy', 'steel ball'],
  },
  {
    id: 'otr-4001-bullet',
    name: 'On The Run OTR.4001 Bullet Tip',
    line: 'Klasický kulatý lihový marker na rychlé tagy',
    price: 129,
    kind: 'marker',
    category: 'fixy',
    hex: '#141416',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 65,
    image: '/products/otr-4001-bullet.webp',
    art: { t: 'marker', tip: 5, finish: 'ink', label: 'OTR 4001' },
    tags: ['bullet nib', 'lihový inkoust'],
  },
  {
    id: 'krink-k75-set',
    name: 'Krink K-75 Paint Marker Set',
    line: 'Legendární brooklynský 7mm zkosený marker s lesklou barvou',
    price: 389,
    kind: 'marker',
    category: 'fixy',
    hex: '#b6b6c0',
    colorCode: 'MTN-1060',
    colorName: 'Silver',
    family: 'neutral',
    inStock: true,
    badge: 'OMEZENÉ',
    stock: 4,
    rating: 4.9,
    reviews: 92,
    image: '/products/krink-k75-set.webp',
    art: { t: 'marker', tip: 15, finish: 'chrome', label: 'KRINK' },
    tags: ['Krink NYC', 'prémiový lak', '7 mm hrot'],
  },
  {
    id: 'dope-solid-stick',
    name: 'Dope Solid Paint Stick',
    line: 'Tuhá olejová barva ve vysouvací tyčince · píše i pod vodou',
    price: 149,
    kind: 'marker',
    category: 'fixy',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 83,
    image: '/products/dope-solid-stick.webp',
    art: { t: 'marker', tip: 15, finish: 'ink', label: 'SOLID' },
    tags: ['solid paint', 'píše na mokro', 'nevysychá'],
  },
  {
    id: 'square-paint-cutter',
    name: 'Square Paint Marker Cutter',
    line: 'Akrylový popisovač se zkoseným kaligrafickým hrotem',
    price: 159,
    kind: 'marker',
    category: 'fixy',
    hex: '#1f63e0',
    family: 'blue',
    inStock: true,
    rating: 4.7,
    reviews: 44,
    image: '/products/square-paint-cutter.webp',
    art: { t: 'marker', tip: 15, finish: 'acrylic', label: 'SQUARE' },
    tags: ['cutter hrot', 'ploché linky'],
  },
  {
    id: 'square-paint-squeezer',
    name: 'Square Paint Squeezer Mop',
    line: 'Měkké tělo na regulaci toku barvy pro šťavnaté kapance',
    price: 169,
    kind: 'marker',
    category: 'fixy',
    hex: '#39d04a',
    family: 'green',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 115,
    image: '/products/square-paint-squeezer.webp',
    art: { t: 'marker', tip: 15, finish: 'ink', label: 'SQUEEZER' },
    tags: ['squeezer', 'drip efekt', 'stlačitelný'],
  },
  {
    id: 'square-paint-refill-200',
    name: 'Square Paint Refill 200ml',
    line: 'Náhradní náplň do akrylových a squeezer markerů',
    price: 249,
    kind: 'marker',
    category: 'fixy',
    hex: '#0e0d10',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 57,
    image: '/products/square-paint-refill-200.webp',
    art: { t: 'refill' },
    tags: ['200 ml', 'dolití fixů', 'vysoká kryvost'],
  },

  /* ── TRYSKY ─────────────────────────────────────────────────── */
  {
    id: 'level-1-ultraskinny',
    name: 'Level 1 Ultra Skinny Cap',
    line: 'Nejjemnější linka 4–15 mm · pro detailní stínování',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#ffffff',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 194,
    image: '/products/level-1-ultraskinny.webp',
    art: { t: 'cap', style: 'skinny' },
    tags: ['0.4–1.5 cm', 'detail', 'čistá linka'],
  },
  {
    id: 'level-2-fine-skinny',
    name: 'Level 2 Fine Skinny Cap',
    line: 'Jemná obrysová linka 6–25 mm · outline standard',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#0e0d10',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.8,
    reviews: 156,
    image: '/products/level-2-fine-skinny.webp',
    art: { t: 'cap', style: 'skinny' },
    tags: ['0.6–2.5 cm', 'outline', 'přesnost'],
  },
  {
    id: 'level-3-skinny',
    name: 'Level 3 Skinny Cap',
    line: 'Střední univerzální linka 10–40 mm',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#1a48b6',
    family: 'blue',
    inStock: true,
    rating: 4.7,
    reviews: 108,
    image: '/products/level-3-skinny.webp',
    art: { t: 'cap', style: 'skinny' },
    tags: ['1–4 cm', 'univerzální linka'],
  },
  {
    id: 'level-4-soft-fat',
    name: 'Level 4 Soft Fat Cap',
    line: 'Měkký široký přechod 30–100 mm · ideální na fade',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#39d04a',
    family: 'green',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 132,
    image: '/products/level-4-soft-fat.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['3–10 cm', 'přechody a stíny'],
  },
  {
    id: 'level-5-fat',
    name: 'Level 5 Fat Cap',
    line: 'Široká stopa 40–150 mm na rychlé vybarvení ploch',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#f4c21a',
    family: 'yellow',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 210,
    image: '/products/level-5-fat.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['4–15 cm', 'fill-in', 'rychlý nástřik'],
  },
  {
    id: 'level-6-ultra-fat',
    name: 'Level 6 Ultra Fat Cap',
    line: 'Extrémně široká stopa 50–250 mm pro masivní pokrytí',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#d31a25',
    family: 'red',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 188,
    image: '/products/level-6-ultra-fat.webp',
    art: { t: 'cap', style: 'super-fat' },
    tags: ['5–25 cm', 'ultra široká', 'mega tlak'],
  },
  {
    id: 'pink-fat-cap',
    name: 'Pink Fat Cap (Růžový)',
    line: 'Klasická oblíbená tryska na fill-iny a rychlé tagy',
    price: 16,
    kind: 'cap',
    category: 'trysky',
    hex: '#ed3a8e',
    family: 'pink',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 245,
    image: '/products/pink-fat-cap.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['klasika', 'rychlý výdej barvy'],
  },
  {
    id: 'orange-fat-cap',
    name: 'Orange Fat Cap (Oranžový)',
    line: 'Středně měkká fat tryska s čistým kruhovým rozprachem',
    price: 16,
    kind: 'cap',
    category: 'trysky',
    hex: '#e25a15',
    family: 'orange',
    inStock: true,
    rating: 4.8,
    reviews: 98,
    image: '/products/orange-fat-cap.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['čistý rozprach', 'fat cap'],
  },
  {
    id: 'astro-fat-cap',
    name: 'Astro Fat Cap',
    line: 'Nejširší klasická tryska na trhu · extrémní tok barvy',
    price: 19,
    kind: 'cap',
    category: 'trysky',
    hex: '#ffffff',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 167,
    image: '/products/astro-fat-cap.webp',
    art: { t: 'cap', style: 'super-fat' },
    tags: ['astro', 'maximální stopa', 'bomby'],
  },
  {
    id: 'ny-fat-cap',
    name: 'New York Fat Cap',
    line: 'Legendární oldschool tryska z newyorského metra',
    price: 19,
    kind: 'cap',
    category: 'trysky',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 5.0,
    reviews: 289,
    image: '/products/ny-fat-cap.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['NY classic', 'legendární kužel'],
  },
  {
    id: 'gold-fat-cap',
    name: 'Gold Fat Cap (Zlatý)',
    line: 'Optimalizovaná tryska pro Montana GOLD a nízký tlak',
    price: 18,
    kind: 'cap',
    category: 'trysky',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    rating: 4.8,
    reviews: 84,
    image: '/products/gold-fat-cap.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['pro nízký tlak', 'zlatá tryska'],
  },
  {
    id: 'needle-cap-red',
    name: 'Needle Cap Red (Jehlová)',
    line: 'Dostřik až do 2 metrů · trubičková stříkací jehla',
    price: 22,
    kind: 'cap',
    category: 'trysky',
    hex: '#d31a25',
    family: 'red',
    inStock: true,
    badge: 'TIP',
    rating: 4.7,
    reviews: 76,
    image: '/products/needle-cap-red.webp',
    art: { t: 'cap', style: 'skinny' },
    tags: ['dostřik do výšky', 'jehlová tryska'],
  },
  {
    id: 'calligraphy-cap',
    name: 'Calligraphy Cap',
    line: 'Plochá otočná tryska pro kaligrafický štětcový efekt',
    price: 19,
    kind: 'cap',
    category: 'trysky',
    hex: '#141418',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 62,
    image: '/products/calligraphy-cap.webp',
    art: { t: 'cap', style: 'calligraphy' },
    tags: ['plochý nástřik', 'kaligrafie'],
  },
  {
    id: 'universal-cap',
    name: 'Universal Cap (Banana Yellow)',
    line: 'Univerzální tryska kompatibilní s 99 % sprejů',
    price: 15,
    kind: 'cap',
    category: 'trysky',
    hex: '#fce53a',
    family: 'yellow',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.8,
    reviews: 154,
    image: '/products/universal-cap.webp',
    art: { t: 'cap', style: 'universal' },
    tags: ['univerzál', 'sedí na všechno'],
  },
  {
    id: 'flux-cap-10pack',
    name: 'Flux Cap (10 ks Pack)',
    line: 'Balení 10 ks rychlých nástřikových trysek',
    price: 149,
    kind: 'cap',
    category: 'trysky',
    hex: '#ff8a2a',
    family: 'orange',
    inStock: true,
    badge: 'PACK',
    rating: 4.8,
    reviews: 88,
    image: '/products/flux-cap-10pack.webp',
    art: { t: 'cap', style: 'fat' },
    tags: ['10 ks pack', 'výhodné balení'],
  },

  /* ── OBLEČENÍ ───────────────────────────────────────────────── */
  {
    id: 'montana-tshirt-logo-white',
    name: 'Tričko Montana Logo White',
    line: '100% bavlna 200 gsm · klasický potisk Montana Cans',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#ffffff',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 82,
    image: '/products/montana-tshirt-white.webp',
    art: { t: 'apparel', cut: 'tee', print: 'MTN' },
    tags: ['S–XXL', '100% bavlna', 'bílý základ'],
  },
  {
    id: 'montana-tshirt-typo-black',
    name: 'Tričko Montana Typo Logo Black',
    line: 'Heavy 220 gsm bavlna · potisk na hrudi i zádech',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.8,
    reviews: 64,
    image: '/products/montana-tshirt-typo-black.webp',
    art: { t: 'apparel', cut: 'tee', print: 'TAG' },
    tags: ['S–XXL', 'heavy bavlna', 'černá'],
  },
  {
    id: 'montana-tshirt-line-black',
    name: 'Tričko Montana Typo Line Shirt',
    line: 'Černé street triko s jemnou lineární grafikou',
    price: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#16151a',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 39,
    image: '/products/montana-tshirt-line-black.webp',
    art: { t: 'apparel', cut: 'tee', print: 'THROW' },
    tags: ['S–XXL', 'line logo'],
  },
  {
    id: 'montana-tshirt-cloak',
    name: 'Tričko Montana Cloak Front',
    line: 'Oversize střih s masivním autorským potiskem',
    price: 790,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#141318',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 51,
    image: '/products/montana-tshirt-cloak.webp',
    art: { t: 'apparel', cut: 'tee', print: 'MTN' },
    tags: ['oversize', 'autorský design'],
  },
  {
    id: 'montana-tshirt-fb-blue',
    name: 'Tričko Montana FB Blue',
    line: 'Tyrkysově modré bavlněné triko s Montana brandingem',
    price: 590,
    oldPrice: 690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#21c4d1',
    family: 'blue',
    inStock: true,
    badge: 'SLEVA',
    rating: 4.6,
    reviews: 33,
    image: '/products/montana-tshirt-fb-blue.webp',
    art: { t: 'apparel', cut: 'tee', print: 'MTN' },
    tags: ['sleva', 'modrá'],
  },
  {
    id: 'montana-hoody-black-zip',
    name: 'Mikina Montana Cans Black Zip',
    line: 'Kvalitní 380 gsm zipová mikina s kapucí a výšivkou',
    price: 1590,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#0e0d10',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 118,
    image: '/products/montana-hoody-black-zip.webp',
    art: { t: 'apparel', cut: 'hoodie', print: 'MTN' },
    tags: ['380 gsm', 'zipová', 'výšivka'],
  },
  {
    id: 'montana-hoody-grey-zip',
    name: 'Mikina Montana Logo Zipper Grey',
    line: 'Šedý melír · teplá fleece podšívka a kovový zip',
    price: 1590,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#6c6b73',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 74,
    image: '/products/montana-hoody-grey-zip.webp',
    art: { t: 'apparel', cut: 'hoodie', print: 'MTN' },
    tags: ['šedý melír', 'fleece podšívka'],
  },
  {
    id: 'montana-hoody-tag-green',
    name: 'Mikina Montana Ziphoody Tag Shapiro Green',
    line: 'Limitovaná edice ve smaragdově zelené barvě s tagem Shapiro',
    price: 1690,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#1a5c4e',
    family: 'green',
    inStock: true,
    stock: 4,
    badge: 'OMEZENÉ',
    rating: 5.0,
    reviews: 46,
    image: '/products/montana-hoody-tag-green.webp',
    art: { t: 'apparel', cut: 'hoodie', print: 'TAG' },
    tags: ['limitka', 'Shapiro edice', 'zelená'],
  },
  {
    id: 'montana-hoody-typo-charcoal',
    name: 'Mikina Montana Typo Logo Charcoal',
    line: 'Tmavě šedý charcoal odstín · heavy weight bavlna',
    price: 1490,
    kind: 'apparel',
    category: 'obleceni',
    hex: '#34313c',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 59,
    image: '/products/montana-hoody-typo-charcoal.webp',
    art: { t: 'apparel', cut: 'hoodie', print: 'ACID' },
    tags: ['charcoal', 'klokanka'],
  },

  /* ── DOPLŇKY ────────────────────────────────────────────────── */
  {
    id: 'montana-blackbook-a4',
    name: 'Blackbook Montana Cans A4',
    line: '144 stran · 120 gsm papír nepropouštějící lihové fixy',
    price: 549,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 234,
    image: '/products/montana-blackbook-a4.webp',
    art: { t: 'book', size: 'A4' },
    tags: ['tvrdé desky', '144 stran', 'nepropouští fixy'],
  },
  {
    id: 'montana-sketchbook-landscape',
    name: 'Montana Sketchbook Landscape 15×21',
    line: 'Kompaktní šířkový formát pro panoramatické skici',
    price: 389,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#8a8990',
    family: 'neutral',
    inStock: true,
    rating: 4.8,
    reviews: 94,
    image: '/products/montana-sketchbook-landscape.webp',
    art: { t: 'book', size: 'A5' },
    tags: ['šířkový formát', 'na cesty'],
  },
  {
    id: 'montana-gloves-black',
    name: 'Rukavice Montana Cans (2 ks)',
    line: 'Protiskluzové pracovní rukavice pro přesný úchop spreje',
    price: 99,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#121214',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.8,
    reviews: 165,
    image: '/products/montana-gloves-black.webp',
    art: { t: 'gloves' },
    tags: ['ochrana rukou', 'protiskluz'],
  },
  {
    id: 'protective-gloves-latex',
    name: 'Ochranné nitrilové rukavice (2 ks)',
    line: 'Černé tenké rukavice odolné vůči rozpouštědlům',
    price: 29,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#25232c',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 110,
    image: '/products/protective-gloves-latex.webp',
    art: { t: 'gloves' },
    tags: ['jednorázové', 'chemická odolnost'],
  },
  {
    id: 'montana-gloves-nylon',
    name: 'Montana Nylon Grip Gloves',
    line: 'Nylonové bezešvé rukavice s polyuretanovým zátěrem',
    price: 119,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#383640',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 78,
    image: '/products/montana-gloves-nylon.webp',
    art: { t: 'gloves' },
    tags: ['bezešvé', 'perfektní cit v prstech'],
  },
  {
    id: 'montana-hologram-stickers',
    name: 'Montana Cans Hologram Egg Shell Stickers',
    line: 'Neroztrhnutelné samolepky s hologramem · nelze strhnout v celku',
    price: 249,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#d4b248',
    family: 'yellow',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 5.0,
    reviews: 198,
    image: '/products/montana-hologram-stickers.webp',
    art: { t: 'stencil' },
    tags: ['egg shell', 'hologram', '50 ks'],
  },
  {
    id: 'mr-serious-bag-12',
    name: 'Brašna Mr. Serious Shoulder 12 Cans',
    line: 'Vypolstrovaná taška přes rameno přesně na 12 sprejů',
    price: 990,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#1b1a1f',
    family: 'neutral',
    inStock: true,
    badge: 'BESTSELLER',
    rating: 4.9,
    reviews: 142,
    image: '/products/mr-serious-bag-12.webp',
    art: { t: 'bag' },
    tags: ['12 sprejů', 'polstrované přihrádky', 'tichý zip'],
  },
  {
    id: 'mr-serious-bag-18',
    name: 'Brašna Mr. Serious Shoulder 18 Cans',
    line: 'Extra prostorná brašna na 18 sprejů + kapsy na trysky',
    price: 1290,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#141318',
    family: 'neutral',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 97,
    image: '/products/mr-serious-bag-18.webp',
    art: { t: 'bag' },
    tags: ['18 sprejů', 'vysoká nosnost'],
  },
  {
    id: 'montana-pp-panel-bag',
    name: 'Montana PP Panel Bag',
    line: 'Pevná omyvatelná polypropylenová taška na 6 sprejů',
    price: 199,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#25232c',
    family: 'neutral',
    inStock: true,
    rating: 4.7,
    reviews: 68,
    image: '/products/montana-pp-panel-bag.webp',
    art: { t: 'bag' },
    tags: ['6 sprejů', 'voděodolná'],
  },
  {
    id: 'graffshop-brno-canvas-bag',
    name: 'Plátěná taška Graffshop Brno',
    line: '100% bavlna · ekologická taška s potiskem brněnského shopu',
    price: 149,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#efece4',
    family: 'neutral',
    inStock: true,
    badge: 'NOVÉ',
    rating: 4.8,
    reviews: 53,
    image: '/products/graffshop-brno-bag.webp',
    art: { t: 'bag' },
    tags: ['Graffshop Brno', 'plátěnka'],
  },
  {
    id: 'book-graffiti-cookbook',
    name: 'Kniha: The Graffiti Cookbook',
    line: 'Kompletní průvodce technikami, materiály a styly graffiti',
    price: 690,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#ffd400',
    family: 'yellow',
    inStock: true,
    badge: 'TIP',
    rating: 4.9,
    reviews: 86,
    image: '/products/book-graffiti-cookbook.webp',
    art: { t: 'book', size: 'A4' },
    tags: ['kniha', '140 stran', 'techniky & historie'],
  },
  {
    id: 'book-urban-scrawl',
    name: 'Kniha: Urban Scrawl',
    line: 'Kniha street artu, tagů a typografie z celého světa',
    price: 650,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#e84a27',
    family: 'red',
    inStock: true,
    stock: 3,
    badge: 'OMEZENÉ',
    rating: 4.8,
    reviews: 42,
    image: '/products/book-urban-scrawl.webp',
    art: { t: 'book', size: 'square' },
    tags: ['kniha', 'street art'],
  },
  {
    id: 'book-for-me-and-my-homies',
    name: 'Kniha: For Me and My Homies',
    line: 'Fotopublikace mapující undergroundovou scénu a vlakové pieces',
    price: 790,
    kind: 'accessory',
    category: 'doplnky',
    hex: '#25232c',
    family: 'neutral',
    inStock: true,
    rating: 5.0,
    reviews: 67,
    image: '/products/book-for-me-and-my-homies.webp',
    art: { t: 'book', size: 'A4' },
    tags: ['fotokniha', 'limitovaný náklad'],
  },
];

/** Sort modes offered in the catalogue toolbar. */
export type SortMode = 'doporucene' | 'nejlevnejsi' | 'nejdrazsi' | 'hodnoceni' | 'novinky';

export const SORTS: { id: SortMode; label: string }[] = [
  { id: 'doporucene', label: 'Doporučené' },
  { id: 'novinky', label: 'Novinky' },
  { id: 'nejlevnejsi', label: 'Nejlevnější' },
  { id: 'nejdrazsi', label: 'Nejdražší' },
  { id: 'hodnoceni', label: 'Nejlépe hodnocené' },
];

export function sortProducts(list: Product[], mode: SortMode): Product[] {
  const out = [...list];
  switch (mode) {
    case 'nejlevnejsi':
      return out.sort((a, b) => a.price - b.price);
    case 'nejdrazsi':
      return out.sort((a, b) => b.price - a.price);
    case 'hodnoceni':
      return out.sort((a, b) => b.rating - a.rating || b.reviews - a.reviews);
    case 'novinky':
      return out.sort(
        (a, b) => Number(b.badge === 'NOVÉ') - Number(a.badge === 'NOVÉ') || b.reviews - a.reviews,
      );
    default:
      /* "Doporučené" = in stock first, then by how much social proof it has. */
      return out.sort(
        (a, b) => Number(b.inStock) - Number(a.inStock) || b.reviews - a.reviews,
      );
  }
}

/** Czech price formatting — non-breaking space before the currency. */
export function formatPrice(czk: number): string {
  return `${czk.toLocaleString('cs-CZ')} Kč`;
}
